theme: jekyll-theme-Minimal
title: Giulia Lavizzari
description: PhD student at University of Milan Bicocca, doctoral student at CERN, in the CMS experiment.

github:
  is_project_page: false
  is_profile_page: false
